//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

namespace table
{
	public static partial class BibleDataBaseExtensions
	{
		/// <summary>
		/// 通过[大类]二分快速查表
		/// </summary>
		/// <param name="firID">大类</param>
		/// <returns></returns>
		public static IEnumerable<BibleDataBase> Query(this List<BibleDataBase> sorted, uint firID)
		{
			var key = new BibleDataBase() { firID = firID };
			var comparer = new Comparer1();
			var from = sorted.BinarySearch(key, comparer);
			if (from < 0) yield break;
			var to = from + 1;
			while (from > 0 && comparer.Compare(key, sorted[from - 1]) == 0) from--;
			while (to < sorted.Count && comparer.Compare(key, sorted[to]) == 0) to++;
			for (var i = from; i < to; i++) yield return sorted[i];
		}
		/// <summary>
		/// 通过[大类 + 小类]二分快速查表
		/// </summary>
		/// <param name="firID">大类</param>
		/// <param name="secID">小类</param>
		/// <returns></returns>
		public static BibleDataBase Query(this List<BibleDataBase> sorted, uint firID, uint secID)
		{
			var key = new BibleDataBase() { firID = firID, secID = secID };
			var comparer = new Comparer2();
			var index = sorted.BinarySearch(key, comparer);
			return index >= 0 ? sorted[index] : default(BibleDataBase);
		}

		#region Comparer
		class Comparer1 : Comparer<BibleDataBase>
		{
			public override int Compare(BibleDataBase a, BibleDataBase b)
			{
				{ var n = a.firID.CompareTo(b.firID); if (n != 0) return n; }
				return 0;
			}
		}
		class Comparer2 : Comparer<BibleDataBase>
		{
			public override int Compare(BibleDataBase a, BibleDataBase b)
			{
				{ var n = a.firID.CompareTo(b.firID); if (n != 0) return n; }
				{ var n = a.secID.CompareTo(b.secID); if (n != 0) return n; }
				return 0;
			}
		}
		#endregion
	}
}
