//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

namespace table
{
	public static partial class BossTalkDataBaseExtensions
	{
		/// <summary>
		/// 通过[NPCID]二分快速查表
		/// </summary>
		/// <param name="npcID">NPCID</param>
		/// <returns></returns>
		public static BossTalkDataBase Query(this List<BossTalkDataBase> sorted, uint npcID)
		{
			var key = new BossTalkDataBase() { npcID = npcID };
			var comparer = new Comparer1();
			var index = sorted.BinarySearch(key, comparer);
			return index >= 0 ? sorted[index] : default(BossTalkDataBase);
		}

		#region Comparer
		class Comparer1 : Comparer<BossTalkDataBase>
		{
			public override int Compare(BossTalkDataBase a, BossTalkDataBase b)
			{
				{ var n = a.npcID.CompareTo(b.npcID); if (n != 0) return n; }
				return 0;
			}
		}
		#endregion
	}
}
