//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

namespace table
{
	public static partial class BuffDataBaseExtensions
	{
		/// <summary>
		/// 通过[编号]二分快速查表
		/// </summary>
		/// <param name="dwID">编号</param>
		/// <returns></returns>
		public static IEnumerable<BuffDataBase> Query(this List<BuffDataBase> sorted, uint dwID)
		{
			var key = new BuffDataBase() { dwID = dwID };
			var comparer = new Comparer1();
			var from = sorted.BinarySearch(key, comparer);
			if (from < 0) yield break;
			var to = from + 1;
			while (from > 0 && comparer.Compare(key, sorted[from - 1]) == 0) from--;
			while (to < sorted.Count && comparer.Compare(key, sorted[to]) == 0) to++;
			for (var i = from; i < to; i++) yield return sorted[i];
		}
		/// <summary>
		/// 通过[编号 + 等级]二分快速查表
		/// </summary>
		/// <param name="dwID">编号</param>
		/// <param name="buffLevel">等级</param>
		/// <returns></returns>
		public static BuffDataBase Query(this List<BuffDataBase> sorted, uint dwID, uint buffLevel)
		{
			var key = new BuffDataBase() { dwID = dwID, buffLevel = buffLevel };
			var comparer = new Comparer2();
			var index = sorted.BinarySearch(key, comparer);
			return index >= 0 ? sorted[index] : default(BuffDataBase);
		}

		#region Comparer
		class Comparer1 : Comparer<BuffDataBase>
		{
			public override int Compare(BuffDataBase a, BuffDataBase b)
			{
				{ var n = a.dwID.CompareTo(b.dwID); if (n != 0) return n; }
				return 0;
			}
		}
		class Comparer2 : Comparer<BuffDataBase>
		{
			public override int Compare(BuffDataBase a, BuffDataBase b)
			{
				{ var n = a.dwID.CompareTo(b.dwID); if (n != 0) return n; }
				{ var n = a.buffLevel.CompareTo(b.buffLevel); if (n != 0) return n; }
				return 0;
			}
		}
		#endregion
	}
}
