//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

namespace table
{
	public static partial class CangBaoTuDataBaseExtensions
	{
		/// <summary>
		/// 通过[地图ID]二分快速查表
		/// </summary>
		/// <param name="map_id">地图ID</param>
		/// <returns></returns>
		public static CangBaoTuDataBase Query(this List<CangBaoTuDataBase> sorted, uint map_id)
		{
			var key = new CangBaoTuDataBase() { map_id = map_id };
			var comparer = new Comparer1();
			var index = sorted.BinarySearch(key, comparer);
			return index >= 0 ? sorted[index] : default(CangBaoTuDataBase);
		}

		#region Comparer
		class Comparer1 : Comparer<CangBaoTuDataBase>
		{
			public override int Compare(CangBaoTuDataBase a, CangBaoTuDataBase b)
			{
				{ var n = a.map_id.CompareTo(b.map_id); if (n != 0) return n; }
				return 0;
			}
		}
		#endregion
	}
}
