//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

namespace table
{
	public static partial class ClanSkillDataBaseExtensions
	{
		/// <summary>
		/// 通过[SkillID]二分快速查表
		/// </summary>
		/// <param name="skillID">SkillID</param>
		/// <returns></returns>
		public static IEnumerable<ClanSkillDataBase> Query(this List<ClanSkillDataBase> sorted, uint skillID)
		{
			var key = new ClanSkillDataBase() { skillID = skillID };
			var comparer = new Comparer1();
			var from = sorted.BinarySearch(key, comparer);
			if (from < 0) yield break;
			var to = from + 1;
			while (from > 0 && comparer.Compare(key, sorted[from - 1]) == 0) from--;
			while (to < sorted.Count && comparer.Compare(key, sorted[to]) == 0) to++;
			for (var i = from; i < to; i++) yield return sorted[i];
		}
		/// <summary>
		/// 通过[SkillID + 等级]二分快速查表
		/// </summary>
		/// <param name="skillID">SkillID</param>
		/// <param name="lv">等级</param>
		/// <returns></returns>
		public static ClanSkillDataBase Query(this List<ClanSkillDataBase> sorted, uint skillID, uint lv)
		{
			var key = new ClanSkillDataBase() { skillID = skillID, lv = lv };
			var comparer = new Comparer2();
			var index = sorted.BinarySearch(key, comparer);
			return index >= 0 ? sorted[index] : default(ClanSkillDataBase);
		}

		#region Comparer
		class Comparer1 : Comparer<ClanSkillDataBase>
		{
			public override int Compare(ClanSkillDataBase a, ClanSkillDataBase b)
			{
				{ var n = a.skillID.CompareTo(b.skillID); if (n != 0) return n; }
				return 0;
			}
		}
		class Comparer2 : Comparer<ClanSkillDataBase>
		{
			public override int Compare(ClanSkillDataBase a, ClanSkillDataBase b)
			{
				{ var n = a.skillID.CompareTo(b.skillID); if (n != 0) return n; }
				{ var n = a.lv.CompareTo(b.lv); if (n != 0) return n; }
				return 0;
			}
		}
		#endregion
	}
}
