//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

namespace table
{
	public static partial class ConsignmentCateIDConfExtensions
	{
		/// <summary>
		/// 通过[大类ID]二分快速查表
		/// </summary>
		/// <param name="ID">大类ID</param>
		/// <returns></returns>
		public static IEnumerable<ConsignmentCateIDConf> Query(this List<ConsignmentCateIDConf> sorted, uint ID)
		{
			var key = new ConsignmentCateIDConf() { ID = ID };
			var comparer = new Comparer1();
			var from = sorted.BinarySearch(key, comparer);
			if (from < 0) yield break;
			var to = from + 1;
			while (from > 0 && comparer.Compare(key, sorted[from - 1]) == 0) from--;
			while (to < sorted.Count && comparer.Compare(key, sorted[to]) == 0) to++;
			for (var i = from; i < to; i++) yield return sorted[i];
		}
		/// <summary>
		/// 通过[大类ID + 细类ID]二分快速查表
		/// </summary>
		/// <param name="ID">大类ID</param>
		/// <param name="SubID">细类ID</param>
		/// <returns></returns>
		public static ConsignmentCateIDConf Query(this List<ConsignmentCateIDConf> sorted, uint ID, uint SubID)
		{
			var key = new ConsignmentCateIDConf() { ID = ID, SubID = SubID };
			var comparer = new Comparer2();
			var index = sorted.BinarySearch(key, comparer);
			return index >= 0 ? sorted[index] : default(ConsignmentCateIDConf);
		}

		#region Comparer
		class Comparer1 : Comparer<ConsignmentCateIDConf>
		{
			public override int Compare(ConsignmentCateIDConf a, ConsignmentCateIDConf b)
			{
				{ var n = a.ID.CompareTo(b.ID); if (n != 0) return n; }
				return 0;
			}
		}
		class Comparer2 : Comparer<ConsignmentCateIDConf>
		{
			public override int Compare(ConsignmentCateIDConf a, ConsignmentCateIDConf b)
			{
				{ var n = a.ID.CompareTo(b.ID); if (n != 0) return n; }
				{ var n = a.SubID.CompareTo(b.SubID); if (n != 0) return n; }
				return 0;
			}
		}
		#endregion
	}
}
