//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

namespace table
{
	public static partial class CopyTargetDataBaseExtensions
	{
		/// <summary>
		/// 通过[副本ID]二分快速查表
		/// </summary>
		/// <param name="copyId">副本ID</param>
		/// <returns></returns>
		public static IEnumerable<CopyTargetDataBase> Query(this List<CopyTargetDataBase> sorted, uint copyId)
		{
			var key = new CopyTargetDataBase() { copyId = copyId };
			var comparer = new Comparer1();
			var from = sorted.BinarySearch(key, comparer);
			if (from < 0) yield break;
			var to = from + 1;
			while (from > 0 && comparer.Compare(key, sorted[from - 1]) == 0) from--;
			while (to < sorted.Count && comparer.Compare(key, sorted[to]) == 0) to++;
			for (var i = from; i < to; i++) yield return sorted[i];
		}
		/// <summary>
		/// 通过[副本ID + 波数]二分快速查表
		/// </summary>
		/// <param name="copyId">副本ID</param>
		/// <param name="waveId">波数</param>
		/// <returns></returns>
		public static CopyTargetDataBase Query(this List<CopyTargetDataBase> sorted, uint copyId, uint waveId)
		{
			var key = new CopyTargetDataBase() { copyId = copyId, waveId = waveId };
			var comparer = new Comparer2();
			var index = sorted.BinarySearch(key, comparer);
			return index >= 0 ? sorted[index] : default(CopyTargetDataBase);
		}

		#region Comparer
		class Comparer1 : Comparer<CopyTargetDataBase>
		{
			public override int Compare(CopyTargetDataBase a, CopyTargetDataBase b)
			{
				{ var n = a.copyId.CompareTo(b.copyId); if (n != 0) return n; }
				return 0;
			}
		}
		class Comparer2 : Comparer<CopyTargetDataBase>
		{
			public override int Compare(CopyTargetDataBase a, CopyTargetDataBase b)
			{
				{ var n = a.copyId.CompareTo(b.copyId); if (n != 0) return n; }
				{ var n = a.waveId.CompareTo(b.waveId); if (n != 0) return n; }
				return 0;
			}
		}
		#endregion
	}
}
