//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

namespace table
{
	public static partial class CopyDataBaseExtensions
	{
		/// <summary>
		/// 通过[副本ID]二分快速查表
		/// </summary>
		/// <param name="copyId">副本ID</param>
		/// <returns></returns>
		public static CopyDataBase Query(this List<CopyDataBase> sorted, uint copyId)
		{
			var key = new CopyDataBase() { copyId = copyId };
			var comparer = new Comparer1();
			var index = sorted.BinarySearch(key, comparer);
			return index >= 0 ? sorted[index] : default(CopyDataBase);
		}

		#region Comparer
		class Comparer1 : Comparer<CopyDataBase>
		{
			public override int Compare(CopyDataBase a, CopyDataBase b)
			{
				{ var n = a.copyId.CompareTo(b.copyId); if (n != 0) return n; }
				return 0;
			}
		}
		#endregion
	}
}
