//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

namespace table
{
	public static partial class CopyTargetGuideDataBaseExtensions
	{
		/// <summary>
		/// 通过[ID]二分快速查表
		/// </summary>
		/// <param name="Id">ID</param>
		/// <returns></returns>
		public static CopyTargetGuideDataBase Query(this List<CopyTargetGuideDataBase> sorted, uint Id)
		{
			var key = new CopyTargetGuideDataBase() { Id = Id };
			var comparer = new Comparer1();
			var index = sorted.BinarySearch(key, comparer);
			return index >= 0 ? sorted[index] : default(CopyTargetGuideDataBase);
		}

		#region Comparer
		class Comparer1 : Comparer<CopyTargetGuideDataBase>
		{
			public override int Compare(CopyTargetGuideDataBase a, CopyTargetGuideDataBase b)
			{
				{ var n = a.Id.CompareTo(b.Id); if (n != 0) return n; }
				return 0;
			}
		}
		#endregion
	}
}
