//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

namespace table
{
	public static partial class DeliverDatabaseExtensions
	{
		/// <summary>
		/// 通过[传送NPCID]二分快速查表
		/// </summary>
		/// <param name="dwID">传送NPCID</param>
		/// <returns></returns>
		public static DeliverDatabase Query(this List<DeliverDatabase> sorted, uint dwID)
		{
			var key = new DeliverDatabase() { dwID = dwID };
			var comparer = new Comparer1();
			var index = sorted.BinarySearch(key, comparer);
			return index >= 0 ? sorted[index] : default(DeliverDatabase);
		}

		#region Comparer
		class Comparer1 : Comparer<DeliverDatabase>
		{
			public override int Compare(DeliverDatabase a, DeliverDatabase b)
			{
				{ var n = a.dwID.CompareTo(b.dwID); if (n != 0) return n; }
				return 0;
			}
		}
		#endregion
	}
}
