//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

namespace table
{
	public static partial class EffectFuncDataBaseExtensions
	{
		/// <summary>
		/// 通过[作用函数ID]二分快速查表
		/// </summary>
		/// <param name="func_id">作用函数ID</param>
		/// <returns></returns>
		public static EffectFuncDataBase Query(this List<EffectFuncDataBase> sorted, uint func_id)
		{
			var key = new EffectFuncDataBase() { func_id = func_id };
			var comparer = new Comparer1();
			var index = sorted.BinarySearch(key, comparer);
			return index >= 0 ? sorted[index] : default(EffectFuncDataBase);
		}

		#region Comparer
		class Comparer1 : Comparer<EffectFuncDataBase>
		{
			public override int Compare(EffectFuncDataBase a, EffectFuncDataBase b)
			{
				{ var n = a.func_id.CompareTo(b.func_id); if (n != 0) return n; }
				return 0;
			}
		}
		#endregion
	}
}
