//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

namespace table
{
	public static partial class EquipDataBaseExtensions
	{
		/// <summary>
		/// 通过[装备ID]二分快速查表
		/// </summary>
		/// <param name="equipID">装备ID</param>
		/// <returns></returns>
		public static EquipDataBase Query(this List<EquipDataBase> sorted, uint equipID)
		{
			var key = new EquipDataBase() { equipID = equipID };
			var comparer = new Comparer1();
			var index = sorted.BinarySearch(key, comparer);
			return index >= 0 ? sorted[index] : default(EquipDataBase);
		}

		#region Comparer
		class Comparer1 : Comparer<EquipDataBase>
		{
			public override int Compare(EquipDataBase a, EquipDataBase b)
			{
				{ var n = a.equipID.CompareTo(b.equipID); if (n != 0) return n; }
				return 0;
			}
		}
		#endregion
	}
}
