//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

namespace table
{
	public static partial class EquipRefineDataBaseExtensions
	{
		/// <summary>
		/// 通过[装备ID]二分快速查表
		/// </summary>
		/// <param name="equipId">装备ID</param>
		/// <returns></returns>
		public static IEnumerable<EquipRefineDataBase> Query(this List<EquipRefineDataBase> sorted, uint equipId)
		{
			var key = new EquipRefineDataBase() { equipId = equipId };
			var comparer = new Comparer1();
			var from = sorted.BinarySearch(key, comparer);
			if (from < 0) yield break;
			var to = from + 1;
			while (from > 0 && comparer.Compare(key, sorted[from - 1]) == 0) from--;
			while (to < sorted.Count && comparer.Compare(key, sorted[to]) == 0) to++;
			for (var i = from; i < to; i++) yield return sorted[i];
		}
		/// <summary>
		/// 通过[装备ID + 精炼等级]二分快速查表
		/// </summary>
		/// <param name="equipId">装备ID</param>
		/// <param name="refineLev">精炼等级</param>
		/// <returns></returns>
		public static EquipRefineDataBase Query(this List<EquipRefineDataBase> sorted, uint equipId, byte refineLev)
		{
			var key = new EquipRefineDataBase() { equipId = equipId, refineLev = refineLev };
			var comparer = new Comparer2();
			var index = sorted.BinarySearch(key, comparer);
			return index >= 0 ? sorted[index] : default(EquipRefineDataBase);
		}

		#region Comparer
		class Comparer1 : Comparer<EquipRefineDataBase>
		{
			public override int Compare(EquipRefineDataBase a, EquipRefineDataBase b)
			{
				{ var n = a.equipId.CompareTo(b.equipId); if (n != 0) return n; }
				return 0;
			}
		}
		class Comparer2 : Comparer<EquipRefineDataBase>
		{
			public override int Compare(EquipRefineDataBase a, EquipRefineDataBase b)
			{
				{ var n = a.equipId.CompareTo(b.equipId); if (n != 0) return n; }
				{ var n = a.refineLev.CompareTo(b.refineLev); if (n != 0) return n; }
				return 0;
			}
		}
		#endregion
	}
}
