//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

namespace table
{
	public static partial class GameGlobalConfigExtensions
	{
		/// <summary>
		/// 通过[编号]二分快速查表
		/// </summary>
		/// <param name="TableID">编号</param>
		/// <returns></returns>
		public static GameGlobalConfig Query(this List<GameGlobalConfig> sorted, uint TableID)
		{
			var key = new GameGlobalConfig() { TableID = TableID };
			var comparer = new Comparer1();
			var index = sorted.BinarySearch(key, comparer);
			return index >= 0 ? sorted[index] : default(GameGlobalConfig);
		}

		#region Comparer
		class Comparer1 : Comparer<GameGlobalConfig>
		{
			public override int Compare(GameGlobalConfig a, GameGlobalConfig b)
			{
				{ var n = a.TableID.CompareTo(b.TableID); if (n != 0) return n; }
				return 0;
			}
		}
		#endregion
	}
}
