//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

namespace table
{
	public static partial class GrowUpRecommendFightPowerDabaBaseExtensions
	{
		/// <summary>
		/// 通过[等级]二分快速查表
		/// </summary>
		/// <param name="Lv">等级</param>
		/// <returns></returns>
		public static GrowUpRecommendFightPowerDabaBase Query(this List<GrowUpRecommendFightPowerDabaBase> sorted, uint Lv)
		{
			var key = new GrowUpRecommendFightPowerDabaBase() { Lv = Lv };
			var comparer = new Comparer1();
			var index = sorted.BinarySearch(key, comparer);
			return index >= 0 ? sorted[index] : default(GrowUpRecommendFightPowerDabaBase);
		}

		#region Comparer
		class Comparer1 : Comparer<GrowUpRecommendFightPowerDabaBase>
		{
			public override int Compare(GrowUpRecommendFightPowerDabaBase a, GrowUpRecommendFightPowerDabaBase b)
			{
				{ var n = a.Lv.CompareTo(b.Lv); if (n != 0) return n; }
				return 0;
			}
		}
		#endregion
	}
}
