//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

namespace table
{
	public static partial class HeartSkillDataBaseExtensions
	{
		/// <summary>
		/// 通过[编号]二分快速查表
		/// </summary>
		/// <param name="id">编号</param>
		/// <returns></returns>
		public static IEnumerable<HeartSkillDataBase> Query(this List<HeartSkillDataBase> sorted, uint id)
		{
			var key = new HeartSkillDataBase() { id = id };
			var comparer = new Comparer1();
			var from = sorted.BinarySearch(key, comparer);
			if (from < 0) yield break;
			var to = from + 1;
			while (from > 0 && comparer.Compare(key, sorted[from - 1]) == 0) from--;
			while (to < sorted.Count && comparer.Compare(key, sorted[to]) == 0) to++;
			for (var i = from; i < to; i++) yield return sorted[i];
		}
		/// <summary>
		/// 通过[编号 + 等级]二分快速查表
		/// </summary>
		/// <param name="id">编号</param>
		/// <param name="lv">等级</param>
		/// <returns></returns>
		public static HeartSkillDataBase Query(this List<HeartSkillDataBase> sorted, uint id, uint lv)
		{
			var key = new HeartSkillDataBase() { id = id, lv = lv };
			var comparer = new Comparer2();
			var index = sorted.BinarySearch(key, comparer);
			return index >= 0 ? sorted[index] : default(HeartSkillDataBase);
		}

		#region Comparer
		class Comparer1 : Comparer<HeartSkillDataBase>
		{
			public override int Compare(HeartSkillDataBase a, HeartSkillDataBase b)
			{
				{ var n = a.id.CompareTo(b.id); if (n != 0) return n; }
				return 0;
			}
		}
		class Comparer2 : Comparer<HeartSkillDataBase>
		{
			public override int Compare(HeartSkillDataBase a, HeartSkillDataBase b)
			{
				{ var n = a.id.CompareTo(b.id); if (n != 0) return n; }
				{ var n = a.lv.CompareTo(b.lv); if (n != 0) return n; }
				return 0;
			}
		}
		#endregion
	}
}
