//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

namespace table
{
	public static partial class HomeLandViewDatabaseExtensions
	{
		/// <summary>
		/// 通过[索引ID]二分快速查表
		/// </summary>
		/// <param name="wdID">索引ID</param>
		/// <returns></returns>
		public static IEnumerable<HomeLandViewDatabase> Query(this List<HomeLandViewDatabase> sorted, ushort wdID)
		{
			var key = new HomeLandViewDatabase() { wdID = wdID };
			var comparer = new Comparer1();
			var from = sorted.BinarySearch(key, comparer);
			if (from < 0) yield break;
			var to = from + 1;
			while (from > 0 && comparer.Compare(key, sorted[from - 1]) == 0) from--;
			while (to < sorted.Count && comparer.Compare(key, sorted[to]) == 0) to++;
			for (var i = from; i < to; i++) yield return sorted[i];
		}
		/// <summary>
		/// 通过[索引ID + 状态]二分快速查表
		/// </summary>
		/// <param name="wdID">索引ID</param>
		/// <param name="wdState">状态</param>
		/// <returns></returns>
		public static HomeLandViewDatabase Query(this List<HomeLandViewDatabase> sorted, ushort wdID, ushort wdState)
		{
			var key = new HomeLandViewDatabase() { wdID = wdID, wdState = wdState };
			var comparer = new Comparer2();
			var index = sorted.BinarySearch(key, comparer);
			return index >= 0 ? sorted[index] : default(HomeLandViewDatabase);
		}

		#region Comparer
		class Comparer1 : Comparer<HomeLandViewDatabase>
		{
			public override int Compare(HomeLandViewDatabase a, HomeLandViewDatabase b)
			{
				{ var n = a.wdID.CompareTo(b.wdID); if (n != 0) return n; }
				return 0;
			}
		}
		class Comparer2 : Comparer<HomeLandViewDatabase>
		{
			public override int Compare(HomeLandViewDatabase a, HomeLandViewDatabase b)
			{
				{ var n = a.wdID.CompareTo(b.wdID); if (n != 0) return n; }
				{ var n = a.wdState.CompareTo(b.wdState); if (n != 0) return n; }
				return 0;
			}
		}
		#endregion
	}
}
