//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

namespace table
{
	public static partial class HomeTradeDataBaseExtensions
	{
		/// <summary>
		/// 通过[索引ID]二分快速查表
		/// </summary>
		/// <param name="indexId">索引ID</param>
		/// <returns></returns>
		public static HomeTradeDataBase Query(this List<HomeTradeDataBase> sorted, uint indexId)
		{
			var key = new HomeTradeDataBase() { indexId = indexId };
			var comparer = new Comparer1();
			var index = sorted.BinarySearch(key, comparer);
			return index >= 0 ? sorted[index] : default(HomeTradeDataBase);
		}

		#region Comparer
		class Comparer1 : Comparer<HomeTradeDataBase>
		{
			public override int Compare(HomeTradeDataBase a, HomeTradeDataBase b)
			{
				{ var n = a.indexId.CompareTo(b.indexId); if (n != 0) return n; }
				return 0;
			}
		}
		#endregion
	}
}
