//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

namespace table
{
	public static partial class HoursemanShipUPLevelExtensions
	{
		/// <summary>
		/// 通过[等级]二分快速查表
		/// </summary>
		/// <param name="levelID">等级</param>
		/// <returns></returns>
		public static HoursemanShipUPLevel Query(this List<HoursemanShipUPLevel> sorted, uint levelID)
		{
			var key = new HoursemanShipUPLevel() { levelID = levelID };
			var comparer = new Comparer1();
			var index = sorted.BinarySearch(key, comparer);
			return index >= 0 ? sorted[index] : default(HoursemanShipUPLevel);
		}

		#region Comparer
		class Comparer1 : Comparer<HoursemanShipUPLevel>
		{
			public override int Compare(HoursemanShipUPLevel a, HoursemanShipUPLevel b)
			{
				{ var n = a.levelID.CompareTo(b.levelID); if (n != 0) return n; }
				return 0;
			}
		}
		#endregion
	}
}
