//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

namespace table
{
	public static partial class IncreaseDataBaseExtensions
	{
		/// <summary>
		/// 通过[索引ID]二分快速查表
		/// </summary>
		/// <param name="dwID">索引ID</param>
		/// <returns></returns>
		public static IEnumerable<IncreaseDataBase> Query(this List<IncreaseDataBase> sorted, uint dwID)
		{
			var key = new IncreaseDataBase() { dwID = dwID };
			var comparer = new Comparer1();
			var from = sorted.BinarySearch(key, comparer);
			if (from < 0) yield break;
			var to = from + 1;
			while (from > 0 && comparer.Compare(key, sorted[from - 1]) == 0) from--;
			while (to < sorted.Count && comparer.Compare(key, sorted[to]) == 0) to++;
			for (var i = from; i < to; i++) yield return sorted[i];
		}
		/// <summary>
		/// 通过[索引ID + 每日使用次数]二分快速查表
		/// </summary>
		/// <param name="dwID">索引ID</param>
		/// <param name="useTimes">每日使用次数</param>
		/// <returns></returns>
		public static IncreaseDataBase Query(this List<IncreaseDataBase> sorted, uint dwID, uint useTimes)
		{
			var key = new IncreaseDataBase() { dwID = dwID, useTimes = useTimes };
			var comparer = new Comparer2();
			var index = sorted.BinarySearch(key, comparer);
			return index >= 0 ? sorted[index] : default(IncreaseDataBase);
		}

		#region Comparer
		class Comparer1 : Comparer<IncreaseDataBase>
		{
			public override int Compare(IncreaseDataBase a, IncreaseDataBase b)
			{
				{ var n = a.dwID.CompareTo(b.dwID); if (n != 0) return n; }
				return 0;
			}
		}
		class Comparer2 : Comparer<IncreaseDataBase>
		{
			public override int Compare(IncreaseDataBase a, IncreaseDataBase b)
			{
				{ var n = a.dwID.CompareTo(b.dwID); if (n != 0) return n; }
				{ var n = a.useTimes.CompareTo(b.useTimes); if (n != 0) return n; }
				return 0;
			}
		}
		#endregion
	}
}
