//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

namespace table
{
	public static partial class ItemBindDataBaseExtensions
	{
		/// <summary>
		/// 通过[绑定标识ID]二分快速查表
		/// </summary>
		/// <param name="bind_id">绑定标识ID</param>
		/// <returns></returns>
		public static ItemBindDataBase Query(this List<ItemBindDataBase> sorted, uint bind_id)
		{
			var key = new ItemBindDataBase() { bind_id = bind_id };
			var comparer = new Comparer1();
			var index = sorted.BinarySearch(key, comparer);
			return index >= 0 ? sorted[index] : default(ItemBindDataBase);
		}

		#region Comparer
		class Comparer1 : Comparer<ItemBindDataBase>
		{
			public override int Compare(ItemBindDataBase a, ItemBindDataBase b)
			{
				{ var n = a.bind_id.CompareTo(b.bind_id); if (n != 0) return n; }
				return 0;
			}
		}
		#endregion
	}
}
