//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

namespace table
{
	public static partial class ItemUseTypeDataBaseExtensions
	{
		/// <summary>
		/// 通过[使用类别ID]二分快速查表
		/// </summary>
		/// <param name="useTypeId">使用类别ID</param>
		/// <returns></returns>
		public static ItemUseTypeDataBase Query(this List<ItemUseTypeDataBase> sorted, uint useTypeId)
		{
			var key = new ItemUseTypeDataBase() { useTypeId = useTypeId };
			var comparer = new Comparer1();
			var index = sorted.BinarySearch(key, comparer);
			return index >= 0 ? sorted[index] : default(ItemUseTypeDataBase);
		}

		#region Comparer
		class Comparer1 : Comparer<ItemUseTypeDataBase>
		{
			public override int Compare(ItemUseTypeDataBase a, ItemUseTypeDataBase b)
			{
				{ var n = a.useTypeId.CompareTo(b.useTypeId); if (n != 0) return n; }
				return 0;
			}
		}
		#endregion
	}
}
