//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

namespace table
{
	public static partial class LandAndFarmDataBaseExtensions
	{
		/// <summary>
		/// 通过[ID]二分快速查表
		/// </summary>
		/// <param name="dwID">ID</param>
		/// <returns></returns>
		public static IEnumerable<LandAndFarmDataBase> Query(this List<LandAndFarmDataBase> sorted, uint dwID)
		{
			var key = new LandAndFarmDataBase() { dwID = dwID };
			var comparer = new Comparer1();
			var from = sorted.BinarySearch(key, comparer);
			if (from < 0) yield break;
			var to = from + 1;
			while (from > 0 && comparer.Compare(key, sorted[from - 1]) == 0) from--;
			while (to < sorted.Count && comparer.Compare(key, sorted[to]) == 0) to++;
			for (var i = from; i < to; i++) yield return sorted[i];
		}
		/// <summary>
		/// 通过[ID + 索引]二分快速查表
		/// </summary>
		/// <param name="dwID">ID</param>
		/// <param name="indexID">索引</param>
		/// <returns></returns>
		public static LandAndFarmDataBase Query(this List<LandAndFarmDataBase> sorted, uint dwID, uint indexID)
		{
			var key = new LandAndFarmDataBase() { dwID = dwID, indexID = indexID };
			var comparer = new Comparer2();
			var index = sorted.BinarySearch(key, comparer);
			return index >= 0 ? sorted[index] : default(LandAndFarmDataBase);
		}

		#region Comparer
		class Comparer1 : Comparer<LandAndFarmDataBase>
		{
			public override int Compare(LandAndFarmDataBase a, LandAndFarmDataBase b)
			{
				{ var n = a.dwID.CompareTo(b.dwID); if (n != 0) return n; }
				return 0;
			}
		}
		class Comparer2 : Comparer<LandAndFarmDataBase>
		{
			public override int Compare(LandAndFarmDataBase a, LandAndFarmDataBase b)
			{
				{ var n = a.dwID.CompareTo(b.dwID); if (n != 0) return n; }
				{ var n = a.indexID.CompareTo(b.indexID); if (n != 0) return n; }
				return 0;
			}
		}
		#endregion
	}
}
