//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

namespace table
{
	public static partial class LangTextDataBaseExtensions
	{
		/// <summary>
		/// 通过[文字ID]二分快速查表
		/// </summary>
		/// <param name="dwID">文字ID</param>
		/// <returns></returns>
		public static LangTextDataBase Query(this List<LangTextDataBase> sorted, uint dwID)
		{
			var key = new LangTextDataBase() { dwID = dwID };
			var comparer = new Comparer1();
			var index = sorted.BinarySearch(key, comparer);
			return index >= 0 ? sorted[index] : default(LangTextDataBase);
		}

		#region Comparer
		class Comparer1 : Comparer<LangTextDataBase>
		{
			public override int Compare(LangTextDataBase a, LangTextDataBase b)
			{
				{ var n = a.dwID.CompareTo(b.dwID); if (n != 0) return n; }
				return 0;
			}
		}
		#endregion
	}
}
