//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

namespace table
{
	public static partial class ModeDiplayDataBaseExtensions
	{
		/// <summary>
		/// 通过[ID]二分快速查表
		/// </summary>
		/// <param name="modeID">ID</param>
		/// <returns></returns>
		public static ModeDiplayDataBase Query(this List<ModeDiplayDataBase> sorted, uint modeID)
		{
			var key = new ModeDiplayDataBase() { modeID = modeID };
			var comparer = new Comparer1();
			var index = sorted.BinarySearch(key, comparer);
			return index >= 0 ? sorted[index] : default(ModeDiplayDataBase);
		}

		#region Comparer
		class Comparer1 : Comparer<ModeDiplayDataBase>
		{
			public override int Compare(ModeDiplayDataBase a, ModeDiplayDataBase b)
			{
				{ var n = a.modeID.CompareTo(b.modeID); if (n != 0) return n; }
				return 0;
			}
		}
		#endregion
	}
}
