//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

namespace table
{
	public static partial class NewFUNCOpenDataBaseExtensions
	{
		/// <summary>
		/// 通过[开启功能ID]二分快速查表
		/// </summary>
		/// <param name="openFuncID">开启功能ID</param>
		/// <returns></returns>
		public static NewFUNCOpenDataBase Query(this List<NewFUNCOpenDataBase> sorted, uint openFuncID)
		{
			var key = new NewFUNCOpenDataBase() { openFuncID = openFuncID };
			var comparer = new Comparer1();
			var index = sorted.BinarySearch(key, comparer);
			return index >= 0 ? sorted[index] : default(NewFUNCOpenDataBase);
		}

		#region Comparer
		class Comparer1 : Comparer<NewFUNCOpenDataBase>
		{
			public override int Compare(NewFUNCOpenDataBase a, NewFUNCOpenDataBase b)
			{
				{ var n = a.openFuncID.CompareTo(b.openFuncID); if (n != 0) return n; }
				return 0;
			}
		}
		#endregion
	}
}
