//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

namespace table
{
	public static partial class PetInHeritDataBaseExtensions
	{
		/// <summary>
		/// 通过[品质]二分快速查表
		/// </summary>
		/// <param name="petQuality">品质</param>
		/// <returns></returns>
		public static PetInHeritDataBase Query(this List<PetInHeritDataBase> sorted, uint petQuality)
		{
			var key = new PetInHeritDataBase() { petQuality = petQuality };
			var comparer = new Comparer1();
			var index = sorted.BinarySearch(key, comparer);
			return index >= 0 ? sorted[index] : default(PetInHeritDataBase);
		}

		#region Comparer
		class Comparer1 : Comparer<PetInHeritDataBase>
		{
			public override int Compare(PetInHeritDataBase a, PetInHeritDataBase b)
			{
				{ var n = a.petQuality.CompareTo(b.petQuality); if (n != 0) return n; }
				return 0;
			}
		}
		#endregion
	}
}
