//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

namespace table
{
	public static partial class PetRecommendDataBaseExtensions
	{
		/// <summary>
		/// 通过[战魂类型]二分快速查表
		/// </summary>
		/// <param name="petType">战魂类型</param>
		/// <returns></returns>
		public static IEnumerable<PetRecommendDataBase> Query(this List<PetRecommendDataBase> sorted, uint petType)
		{
			var key = new PetRecommendDataBase() { petType = petType };
			var comparer = new Comparer1();
			var from = sorted.BinarySearch(key, comparer);
			if (from < 0) yield break;
			var to = from + 1;
			while (from > 0 && comparer.Compare(key, sorted[from - 1]) == 0) from--;
			while (to < sorted.Count && comparer.Compare(key, sorted[to]) == 0) to++;
			for (var i = from; i < to; i++) yield return sorted[i];
		}
		/// <summary>
		/// 通过[战魂类型 + 战魂性格]二分快速查表
		/// </summary>
		/// <param name="petType">战魂类型</param>
		/// <param name="petCharacter">战魂性格</param>
		/// <returns></returns>
		public static PetRecommendDataBase Query(this List<PetRecommendDataBase> sorted, uint petType, uint petCharacter)
		{
			var key = new PetRecommendDataBase() { petType = petType, petCharacter = petCharacter };
			var comparer = new Comparer2();
			var index = sorted.BinarySearch(key, comparer);
			return index >= 0 ? sorted[index] : default(PetRecommendDataBase);
		}

		#region Comparer
		class Comparer1 : Comparer<PetRecommendDataBase>
		{
			public override int Compare(PetRecommendDataBase a, PetRecommendDataBase b)
			{
				{ var n = a.petType.CompareTo(b.petType); if (n != 0) return n; }
				return 0;
			}
		}
		class Comparer2 : Comparer<PetRecommendDataBase>
		{
			public override int Compare(PetRecommendDataBase a, PetRecommendDataBase b)
			{
				{ var n = a.petType.CompareTo(b.petType); if (n != 0) return n; }
				{ var n = a.petCharacter.CompareTo(b.petCharacter); if (n != 0) return n; }
				return 0;
			}
		}
		#endregion
	}
}
