//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

namespace table
{
	public static partial class PetSkillLearnDataBaseExtensions
	{
		/// <summary>
		/// 通过[技能数量]二分快速查表
		/// </summary>
		/// <param name="skillNum">技能数量</param>
		/// <returns></returns>
		public static PetSkillLearnDataBase Query(this List<PetSkillLearnDataBase> sorted, uint skillNum)
		{
			var key = new PetSkillLearnDataBase() { skillNum = skillNum };
			var comparer = new Comparer1();
			var index = sorted.BinarySearch(key, comparer);
			return index >= 0 ? sorted[index] : default(PetSkillLearnDataBase);
		}

		#region Comparer
		class Comparer1 : Comparer<PetSkillLearnDataBase>
		{
			public override int Compare(PetSkillLearnDataBase a, PetSkillLearnDataBase b)
			{
				{ var n = a.skillNum.CompareTo(b.skillNum); if (n != 0) return n; }
				return 0;
			}
		}
		#endregion
	}
}
