//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

namespace table
{
	public static partial class PetSkillLevelUpDataBaseExtensions
	{
		/// <summary>
		/// 通过[技能ID]二分快速查表
		/// </summary>
		/// <param name="skillID">技能ID</param>
		/// <returns></returns>
		public static PetSkillLevelUpDataBase Query(this List<PetSkillLevelUpDataBase> sorted, uint skillID)
		{
			var key = new PetSkillLevelUpDataBase() { skillID = skillID };
			var comparer = new Comparer1();
			var index = sorted.BinarySearch(key, comparer);
			return index >= 0 ? sorted[index] : default(PetSkillLevelUpDataBase);
		}

		#region Comparer
		class Comparer1 : Comparer<PetSkillLevelUpDataBase>
		{
			public override int Compare(PetSkillLevelUpDataBase a, PetSkillLevelUpDataBase b)
			{
				{ var n = a.skillID.CompareTo(b.skillID); if (n != 0) return n; }
				return 0;
			}
		}
		#endregion
	}
}
