//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

namespace table
{
	public static partial class PetUpGradeDataBaseExtensions
	{
		/// <summary>
		/// 通过[等级]二分快速查表
		/// </summary>
		/// <param name="level">等级</param>
		/// <returns></returns>
		public static IEnumerable<PetUpGradeDataBase> Query(this List<PetUpGradeDataBase> sorted, uint level)
		{
			var key = new PetUpGradeDataBase() { level = level };
			var comparer = new Comparer1();
			var from = sorted.BinarySearch(key, comparer);
			if (from < 0) yield break;
			var to = from + 1;
			while (from > 0 && comparer.Compare(key, sorted[from - 1]) == 0) from--;
			while (to < sorted.Count && comparer.Compare(key, sorted[to]) == 0) to++;
			for (var i = from; i < to; i++) yield return sorted[i];
		}
		/// <summary>
		/// 通过[等级 + 宠物ID]二分快速查表
		/// </summary>
		/// <param name="level">等级</param>
		/// <param name="petID">宠物ID</param>
		/// <returns></returns>
		public static PetUpGradeDataBase Query(this List<PetUpGradeDataBase> sorted, uint level, uint petID)
		{
			var key = new PetUpGradeDataBase() { level = level, petID = petID };
			var comparer = new Comparer2();
			var index = sorted.BinarySearch(key, comparer);
			return index >= 0 ? sorted[index] : default(PetUpGradeDataBase);
		}

		#region Comparer
		class Comparer1 : Comparer<PetUpGradeDataBase>
		{
			public override int Compare(PetUpGradeDataBase a, PetUpGradeDataBase b)
			{
				{ var n = a.level.CompareTo(b.level); if (n != 0) return n; }
				return 0;
			}
		}
		class Comparer2 : Comparer<PetUpGradeDataBase>
		{
			public override int Compare(PetUpGradeDataBase a, PetUpGradeDataBase b)
			{
				{ var n = a.level.CompareTo(b.level); if (n != 0) return n; }
				{ var n = a.petID.CompareTo(b.petID); if (n != 0) return n; }
				return 0;
			}
		}
		#endregion
	}
}
