//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

namespace table
{
	public static partial class PkModeExtensions
	{
		/// <summary>
		/// 通过[PK模式]二分快速查表
		/// </summary>
		/// <param name="dwID">PK模式</param>
		/// <returns></returns>
		public static PkMode Query(this List<PkMode> sorted, uint dwID)
		{
			var key = new PkMode() { dwID = dwID };
			var comparer = new Comparer1();
			var index = sorted.BinarySearch(key, comparer);
			return index >= 0 ? sorted[index] : default(PkMode);
		}

		#region Comparer
		class Comparer1 : Comparer<PkMode>
		{
			public override int Compare(PkMode a, PkMode b)
			{
				{ var n = a.dwID.CompareTo(b.dwID); if (n != 0) return n; }
				return 0;
			}
		}
		#endregion
	}
}
