//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

namespace table
{
	public static partial class RankTypeDataBaseExtensions
	{
		/// <summary>
		/// 通过[主类ID]二分快速查表
		/// </summary>
		/// <param name="mainID">主类ID</param>
		/// <returns></returns>
		public static IEnumerable<RankTypeDataBase> Query(this List<RankTypeDataBase> sorted, uint mainID)
		{
			var key = new RankTypeDataBase() { mainID = mainID };
			var comparer = new Comparer1();
			var from = sorted.BinarySearch(key, comparer);
			if (from < 0) yield break;
			var to = from + 1;
			while (from > 0 && comparer.Compare(key, sorted[from - 1]) == 0) from--;
			while (to < sorted.Count && comparer.Compare(key, sorted[to]) == 0) to++;
			for (var i = from; i < to; i++) yield return sorted[i];
		}
		/// <summary>
		/// 通过[主类ID + 子类ID]二分快速查表
		/// </summary>
		/// <param name="mainID">主类ID</param>
		/// <param name="childID">子类ID</param>
		/// <returns></returns>
		public static RankTypeDataBase Query(this List<RankTypeDataBase> sorted, uint mainID, uint childID)
		{
			var key = new RankTypeDataBase() { mainID = mainID, childID = childID };
			var comparer = new Comparer2();
			var index = sorted.BinarySearch(key, comparer);
			return index >= 0 ? sorted[index] : default(RankTypeDataBase);
		}

		#region Comparer
		class Comparer1 : Comparer<RankTypeDataBase>
		{
			public override int Compare(RankTypeDataBase a, RankTypeDataBase b)
			{
				{ var n = a.mainID.CompareTo(b.mainID); if (n != 0) return n; }
				return 0;
			}
		}
		class Comparer2 : Comparer<RankTypeDataBase>
		{
			public override int Compare(RankTypeDataBase a, RankTypeDataBase b)
			{
				{ var n = a.mainID.CompareTo(b.mainID); if (n != 0) return n; }
				{ var n = a.childID.CompareTo(b.childID); if (n != 0) return n; }
				return 0;
			}
		}
		#endregion
	}
}
