//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

namespace table
{
	public static partial class RideExpandDataExtensions
	{
		/// <summary>
		/// 通过[扩充次数]二分快速查表
		/// </summary>
		/// <param name="expandNum">扩充次数</param>
		/// <returns></returns>
		public static RideExpandData Query(this List<RideExpandData> sorted, uint expandNum)
		{
			var key = new RideExpandData() { expandNum = expandNum };
			var comparer = new Comparer1();
			var index = sorted.BinarySearch(key, comparer);
			return index >= 0 ? sorted[index] : default(RideExpandData);
		}

		#region Comparer
		class Comparer1 : Comparer<RideExpandData>
		{
			public override int Compare(RideExpandData a, RideExpandData b)
			{
				{ var n = a.expandNum.CompareTo(b.expandNum); if (n != 0) return n; }
				return 0;
			}
		}
		#endregion
	}
}
