//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

namespace table
{
	public static partial class RideDataBaseExtensions
	{
		/// <summary>
		/// 通过[坐骑ID]二分快速查表
		/// </summary>
		/// <param name="rideID">坐骑ID</param>
		/// <returns></returns>
		public static RideDataBase Query(this List<RideDataBase> sorted, uint rideID)
		{
			var key = new RideDataBase() { rideID = rideID };
			var comparer = new Comparer1();
			var index = sorted.BinarySearch(key, comparer);
			return index >= 0 ? sorted[index] : default(RideDataBase);
		}

		#region Comparer
		class Comparer1 : Comparer<RideDataBase>
		{
			public override int Compare(RideDataBase a, RideDataBase b)
			{
				{ var n = a.rideID.CompareTo(b.rideID); if (n != 0) return n; }
				return 0;
			}
		}
		#endregion
	}
}
