//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

namespace table
{
	public static partial class RunestoneDataBaseExtensions
	{
		/// <summary>
		/// 通过[符石ID]二分快速查表
		/// </summary>
		/// <param name="stoneId">符石ID</param>
		/// <returns></returns>
		public static RunestoneDataBase Query(this List<RunestoneDataBase> sorted, uint stoneId)
		{
			var key = new RunestoneDataBase() { stoneId = stoneId };
			var comparer = new Comparer1();
			var index = sorted.BinarySearch(key, comparer);
			return index >= 0 ? sorted[index] : default(RunestoneDataBase);
		}

		#region Comparer
		class Comparer1 : Comparer<RunestoneDataBase>
		{
			public override int Compare(RunestoneDataBase a, RunestoneDataBase b)
			{
				{ var n = a.stoneId.CompareTo(b.stoneId); if (n != 0) return n; }
				return 0;
			}
		}
		#endregion
	}
}
