//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

namespace table
{
	public static partial class SelectRoleDataBaseExtensions
	{
		/// <summary>
		/// 通过[职业]二分快速查表
		/// </summary>
		/// <param name="professionID">职业</param>
		/// <returns></returns>
		public static IEnumerable<SelectRoleDataBase> Query(this List<SelectRoleDataBase> sorted, uint professionID)
		{
			var key = new SelectRoleDataBase() { professionID = professionID };
			var comparer = new Comparer1();
			var from = sorted.BinarySearch(key, comparer);
			if (from < 0) yield break;
			var to = from + 1;
			while (from > 0 && comparer.Compare(key, sorted[from - 1]) == 0) from--;
			while (to < sorted.Count && comparer.Compare(key, sorted[to]) == 0) to++;
			for (var i = from; i < to; i++) yield return sorted[i];
		}
		/// <summary>
		/// 通过[职业 + 性别]二分快速查表
		/// </summary>
		/// <param name="professionID">职业</param>
		/// <param name="sexID">性别</param>
		/// <returns></returns>
		public static SelectRoleDataBase Query(this List<SelectRoleDataBase> sorted, uint professionID, uint sexID)
		{
			var key = new SelectRoleDataBase() { professionID = professionID, sexID = sexID };
			var comparer = new Comparer2();
			var index = sorted.BinarySearch(key, comparer);
			return index >= 0 ? sorted[index] : default(SelectRoleDataBase);
		}

		#region Comparer
		class Comparer1 : Comparer<SelectRoleDataBase>
		{
			public override int Compare(SelectRoleDataBase a, SelectRoleDataBase b)
			{
				{ var n = a.professionID.CompareTo(b.professionID); if (n != 0) return n; }
				return 0;
			}
		}
		class Comparer2 : Comparer<SelectRoleDataBase>
		{
			public override int Compare(SelectRoleDataBase a, SelectRoleDataBase b)
			{
				{ var n = a.professionID.CompareTo(b.professionID); if (n != 0) return n; }
				{ var n = a.sexID.CompareTo(b.sexID); if (n != 0) return n; }
				return 0;
			}
		}
		#endregion
	}
}
