//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

namespace table
{
	public static partial class SequencerDialogExtensions
	{
		/// <summary>
		/// 通过[对话ID]二分快速查表
		/// </summary>
		/// <param name="ID">对话ID</param>
		/// <returns></returns>
		public static SequencerDialog Query(this List<SequencerDialog> sorted, uint ID)
		{
			var key = new SequencerDialog() { ID = ID };
			var comparer = new Comparer1();
			var index = sorted.BinarySearch(key, comparer);
			return index >= 0 ? sorted[index] : default(SequencerDialog);
		}

		#region Comparer
		class Comparer1 : Comparer<SequencerDialog>
		{
			public override int Compare(SequencerDialog a, SequencerDialog b)
			{
				{ var n = a.ID.CompareTo(b.ID); if (n != 0) return n; }
				return 0;
			}
		}
		#endregion
	}
}
