//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

namespace table
{
	public static partial class SettingDataBaseExtensions
	{
		/// <summary>
		/// 通过[id]二分快速查表
		/// </summary>
		/// <param name="id">id</param>
		/// <returns></returns>
		public static SettingDataBase Query(this List<SettingDataBase> sorted, uint id)
		{
			var key = new SettingDataBase() { id = id };
			var comparer = new Comparer1();
			var index = sorted.BinarySearch(key, comparer);
			return index >= 0 ? sorted[index] : default(SettingDataBase);
		}

		#region Comparer
		class Comparer1 : Comparer<SettingDataBase>
		{
			public override int Compare(SettingDataBase a, SettingDataBase b)
			{
				{ var n = a.id.CompareTo(b.id); if (n != 0) return n; }
				return 0;
			}
		}
		#endregion
	}
}
