//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

namespace table
{
	public static partial class SkillDoubleHitDataBaseExtensions
	{
		/// <summary>
		/// 通过[技能ID]二分快速查表
		/// </summary>
		/// <param name="skillid">技能ID</param>
		/// <returns></returns>
		public static SkillDoubleHitDataBase Query(this List<SkillDoubleHitDataBase> sorted, uint skillid)
		{
			var key = new SkillDoubleHitDataBase() { skillid = skillid };
			var comparer = new Comparer1();
			var index = sorted.BinarySearch(key, comparer);
			return index >= 0 ? sorted[index] : default(SkillDoubleHitDataBase);
		}

		#region Comparer
		class Comparer1 : Comparer<SkillDoubleHitDataBase>
		{
			public override int Compare(SkillDoubleHitDataBase a, SkillDoubleHitDataBase b)
			{
				{ var n = a.skillid.CompareTo(b.skillid); if (n != 0) return n; }
				return 0;
			}
		}
		#endregion
	}
}
