//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

namespace table
{
	public static partial class StoreDataBaseExtensions
	{
		/// <summary>
		/// 通过[索引ID]二分快速查表
		/// </summary>
		/// <param name="mallItemId">索引ID</param>
		/// <returns></returns>
		public static StoreDataBase Query(this List<StoreDataBase> sorted, uint mallItemId)
		{
			var key = new StoreDataBase() { mallItemId = mallItemId };
			var comparer = new Comparer1();
			var index = sorted.BinarySearch(key, comparer);
			return index >= 0 ? sorted[index] : default(StoreDataBase);
		}

		#region Comparer
		class Comparer1 : Comparer<StoreDataBase>
		{
			public override int Compare(StoreDataBase a, StoreDataBase b)
			{
				{ var n = a.mallItemId.CompareTo(b.mallItemId); if (n != 0) return n; }
				return 0;
			}
		}
		#endregion
	}
}
