//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

namespace table
{
	public static partial class TrailerdatabaseExtensions
	{
		/// <summary>
		/// 通过[序号ID]二分快速查表
		/// </summary>
		/// <param name="dwId">序号ID</param>
		/// <returns></returns>
		public static Trailerdatabase Query(this List<Trailerdatabase> sorted, uint dwId)
		{
			var key = new Trailerdatabase() { dwId = dwId };
			var comparer = new Comparer1();
			var index = sorted.BinarySearch(key, comparer);
			return index >= 0 ? sorted[index] : default(Trailerdatabase);
		}

		#region Comparer
		class Comparer1 : Comparer<Trailerdatabase>
		{
			public override int Compare(Trailerdatabase a, Trailerdatabase b)
			{
				{ var n = a.dwId.CompareTo(b.dwId); if (n != 0) return n; }
				return 0;
			}
		}
		#endregion
	}
}
