//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

namespace table
{
	public static partial class UIResourceDataBaseExtensions
	{
		/// <summary>
		/// 通过[UI资源ID]二分快速查表
		/// </summary>
		/// <param name="ID">UI资源ID</param>
		/// <returns></returns>
		public static UIResourceDataBase Query(this List<UIResourceDataBase> sorted, uint ID)
		{
			var key = new UIResourceDataBase() { ID = ID };
			var comparer = new Comparer1();
			var index = sorted.BinarySearch(key, comparer);
			return index >= 0 ? sorted[index] : default(UIResourceDataBase);
		}

		#region Comparer
		class Comparer1 : Comparer<UIResourceDataBase>
		{
			public override int Compare(UIResourceDataBase a, UIResourceDataBase b)
			{
				{ var n = a.ID.CompareTo(b.ID); if (n != 0) return n; }
				return 0;
			}
		}
		#endregion
	}
}
