//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

namespace table
{
	public static partial class UnlockStoreDataBaseExtensions
	{
		/// <summary>
		/// 通过[背包ID]二分快速查表
		/// </summary>
		/// <param name="packId">背包ID</param>
		/// <returns></returns>
		public static IEnumerable<UnlockStoreDataBase> Query(this List<UnlockStoreDataBase> sorted, ushort packId)
		{
			var key = new UnlockStoreDataBase() { packId = packId };
			var comparer = new Comparer1();
			var from = sorted.BinarySearch(key, comparer);
			if (from < 0) yield break;
			var to = from + 1;
			while (from > 0 && comparer.Compare(key, sorted[from - 1]) == 0) from--;
			while (to < sorted.Count && comparer.Compare(key, sorted[to]) == 0) to++;
			for (var i = from; i < to; i++) yield return sorted[i];
		}
		/// <summary>
		/// 通过[背包ID + 解锁序号]二分快速查表
		/// </summary>
		/// <param name="packId">背包ID</param>
		/// <param name="gridIndex">解锁序号</param>
		/// <returns></returns>
		public static UnlockStoreDataBase Query(this List<UnlockStoreDataBase> sorted, ushort packId, ushort gridIndex)
		{
			var key = new UnlockStoreDataBase() { packId = packId, gridIndex = gridIndex };
			var comparer = new Comparer2();
			var index = sorted.BinarySearch(key, comparer);
			return index >= 0 ? sorted[index] : default(UnlockStoreDataBase);
		}

		#region Comparer
		class Comparer1 : Comparer<UnlockStoreDataBase>
		{
			public override int Compare(UnlockStoreDataBase a, UnlockStoreDataBase b)
			{
				{ var n = a.packId.CompareTo(b.packId); if (n != 0) return n; }
				return 0;
			}
		}
		class Comparer2 : Comparer<UnlockStoreDataBase>
		{
			public override int Compare(UnlockStoreDataBase a, UnlockStoreDataBase b)
			{
				{ var n = a.packId.CompareTo(b.packId); if (n != 0) return n; }
				{ var n = a.gridIndex.CompareTo(b.gridIndex); if (n != 0) return n; }
				return 0;
			}
		}
		#endregion
	}
}
