//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

namespace table
{
	public static partial class UpgradeDataBaseExtensions
	{
		/// <summary>
		/// 通过[人物等级]二分快速查表
		/// </summary>
		/// <param name="dwLevel">人物等级</param>
		/// <returns></returns>
		public static UpgradeDataBase Query(this List<UpgradeDataBase> sorted, uint dwLevel)
		{
			var key = new UpgradeDataBase() { dwLevel = dwLevel };
			var comparer = new Comparer1();
			var index = sorted.BinarySearch(key, comparer);
			return index >= 0 ? sorted[index] : default(UpgradeDataBase);
		}

		#region Comparer
		class Comparer1 : Comparer<UpgradeDataBase>
		{
			public override int Compare(UpgradeDataBase a, UpgradeDataBase b)
			{
				{ var n = a.dwLevel.CompareTo(b.dwLevel); if (n != 0) return n; }
				return 0;
			}
		}
		#endregion
	}
}
