//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

namespace table
{
	public static partial class WeaponSoulUpgradeDataBaseExtensions
	{
		/// <summary>
		/// 通过[武魂ID]二分快速查表
		/// </summary>
		/// <param name="id">武魂ID</param>
		/// <returns></returns>
		public static IEnumerable<WeaponSoulUpgradeDataBase> Query(this List<WeaponSoulUpgradeDataBase> sorted, uint id)
		{
			var key = new WeaponSoulUpgradeDataBase() { id = id };
			var comparer = new Comparer1();
			var from = sorted.BinarySearch(key, comparer);
			if (from < 0) yield break;
			var to = from + 1;
			while (from > 0 && comparer.Compare(key, sorted[from - 1]) == 0) from--;
			while (to < sorted.Count && comparer.Compare(key, sorted[to]) == 0) to++;
			for (var i = from; i < to; i++) yield return sorted[i];
		}
		/// <summary>
		/// 通过[武魂ID + 等级]二分快速查表
		/// </summary>
		/// <param name="id">武魂ID</param>
		/// <param name="level">等级</param>
		/// <returns></returns>
		public static WeaponSoulUpgradeDataBase Query(this List<WeaponSoulUpgradeDataBase> sorted, uint id, uint level)
		{
			var key = new WeaponSoulUpgradeDataBase() { id = id, level = level };
			var comparer = new Comparer2();
			var index = sorted.BinarySearch(key, comparer);
			return index >= 0 ? sorted[index] : default(WeaponSoulUpgradeDataBase);
		}

		#region Comparer
		class Comparer1 : Comparer<WeaponSoulUpgradeDataBase>
		{
			public override int Compare(WeaponSoulUpgradeDataBase a, WeaponSoulUpgradeDataBase b)
			{
				{ var n = a.id.CompareTo(b.id); if (n != 0) return n; }
				return 0;
			}
		}
		class Comparer2 : Comparer<WeaponSoulUpgradeDataBase>
		{
			public override int Compare(WeaponSoulUpgradeDataBase a, WeaponSoulUpgradeDataBase b)
			{
				{ var n = a.id.CompareTo(b.id); if (n != 0) return n; }
				{ var n = a.level.CompareTo(b.level); if (n != 0) return n; }
				return 0;
			}
		}
		#endregion
	}
}
